spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test2
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000 #최적화 옵션

  redis:
    host: localhost
    port: 6379
    ttl-duration: 1

logging.level:
  org.hibernate.SQL: debug
  #org.hibernate.type: trace

